steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform=linux/amd64',
      '-t', 'gcr.io/$PROJECT_ID/github.com/farfromavocaido/$REPO_NAME:$COMMIT_SHA',  # Your image tag
      '.'
    ]
  
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/farfromavocaido/$REPO_NAME:$COMMIT_SHA']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        '--image', 'gcr.io/$PROJECT_ID/github.com/farfromavocaido/$REPO_NAME:$COMMIT_SHA',
        '--platform', 'managed',
        '--region', 'europe-west1',  # Updated region
        '--port', '8080',
        '--allow-unauthenticated'
      ]

# Specify the images to push after the build
images:
  - 'gcr.io/$PROJECT_ID/github.com/farfromavocaido/$REPO_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY  # Set logging behaviorg
